apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cntenorio-roleBinding
  namespace: ns-cntenorio
roleRef:
  kind: Role
  name: ns-cntenorio-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: IAM#cntenorio@stemdo.io
  apiGroup: rbac.authorization.k8s.io
