apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cntenorio-roleBinding
  namespace: ns-cntenorio
roleRef:
  kind: Role
  name: ns-cntenorio-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: IAM#serviceid-119cfcaf-2716-42d9-9774-2a7d30c4f2c1 
  apiGroup: rbac.authorization.k8s.io