name: IBM Permissions
run-name: IBM Permissions · ${{ github.event.pull_request.merged && 'Apply' || 'Plan' }}

on:
  pull_request:
    types: [opened, synchronize, closed]
    paths:
      - 'terraform.tfvars'

permissions:
  contents: read
  pull-requests: write
  id-token: write
  issues: write

jobs:
  terraform:
    name: Terraform Plan & Apply
    uses: ./.github/workflows/terraform_ibm_reusable.yml
    with:
      terraform_version: "1.5.7"
      var_files: '["terraform.tfvars"]'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ibm_api_key: ${{ secrets.IBM_CLOUD_API_KEY }}
